#
# Configuration for WebSocket Server only
#

[websocketserver]
adress = 'ws://localhost:8095'
logfile = 'D:/temp/websock.log'
console = true
certFile =
pkFile = 

[develop]
developsystem = true ; Set to false in production
