#
# Configuration for WebSocket Server only
# see also .env_example
[websocketserver]
adress = 'ws://localhost:8095'
logfile = ${LOG_FILE}
console = true
certFile =
pkFile = 
#
# require='true' 
#   only certain js-clients may connect  
#
[jsauth] 
require=true
ssp=${SAVE_SESSION_PATH}
cookie_name = "PHPSESSID"
key = allowconnect
#
# setting determines if tsl is use 
#
[develop]
developsystem = true ; Set to false in production
