#
# Configuration for WebSocket Server only
#
[websocketserver]
adress = 'ws://localhost:8095'
logfile = 'D:/temp/websock.log'
console = true
certFile =
pkFile = 
#
# require='true' 
#   only certain js-clients may connect  
#
[jsauth] 
require=true
cookie_name = "PHPSESSID"
key = allowconnect
#
# setting determines if tsl is use 
#
[develop]
developsystem = true ; Set to false in production
