<?php

include __DIR__ . "/../phpClient/websocketCore.php";

class websocketHuobi extends websocketCore {

    public $uuid, $connected = false, $chunkSize = 6 * 1024;

    //private $socketMaster;

    function __construct($Address, $Port = '', $app = '/', $uu = '') {

        if (parent::__construct($Address, $Port, $app, $uu) == false) {
            return;
        }

        $this->writeSocket('{"op": "sub","cid": "id generated by client","topic": "public.$service.heartbeat"}');
        $respo = $this->readSocket();      
        $xx=zlib_decode($respo);       
        echo var_dump(json_decode($xx));
    }

}

$x = new websocketHuobi("wss://api.hbdm.com", '', '/center-notification');

