<?php

include __DIR__ . "/../phpClient/websocketCore.php";

class websocketHuobi extends websocketCore {

   

    //private $socketMaster;

    function __construct($Address) {

        if (parent::__construct($Address) == false) {
            return;
        }

        $this->writeSocket('{"op": "sub","cid": "id generated by client","topic": "public.$service.heartbeat"}');
        $respo = $this->readSocket();      
        $xx=zlib_decode($respo);       
        echo var_dump(json_decode($xx));
    }

}

$x = new websocketHuobi("wss://api.hbdm.com/center-notification");

